### ISSUE TITLE
Unable to get length of a collection (numItems)

### ISSUE THREAD

**Issue by maverickmueller** [qmasingarbe/pymiere#12]
The intended attribute numItems does not seem to work. Iterating over the collection is still doable though.

But other than that this has been incredible. Sub-request: Please add a link for me to buy you a coffee or something

**Comment by qmasingarbe** [comment]
Using len() on a Collection type object will get you the actual length. It is the recommended way as it is more pythonic.
Nevertheless I added the possibility to directly call the property containing the length on a colllection ( https://github.com/qmasingarbe/pymiere/commit/dd031dffd0951fd5932d4811270d1425f18f028b )
Thanks for your support!
