### ISSUE TITLE
demo_ui.py: Change media path

### ISSUE THREAD

**Issue by PFython** [qmasingarbe/pymiere#18]
I don't recognise the file shown in the Premiere popup message below... pretty sure it's not an image to do with the sample project I have open, and curious to see file extension jpeg not jpg as well...

![image](https://user-images.githubusercontent.com/35893632/98744732-1f365900-23aa-11eb-89f0-9e32de94827a.png)

After I close the popup I get the following:

d:\Pete's Data\OneDrive\Python Scripts\pymiere\demo_ui.py:23: DeprecationWarning: an integer is required (got type sip.voidptr).  Implicit conversion to integers using 
__int__ is deprecated, and may be removed in a future version of Python.
  win32gui.SetForegroundWindow(self.ui_id)
<class 'pywintypes.error'> (0, 'SetForegroundWindow', 'No error message is available') <traceback object at 0x0000023EBF2546C0>
Traceback (most recent call last):
  File "d:\Pete's Data\OneDrive\Python Scripts\pymiere\demo_ui.py", line 23, in wrapper
    win32gui.SetForegroundWindow(self.ui_id)
pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')

**Comment by qmasingarbe** [comment]
This is due to an hardcoded path I left during testing, fixed by https://github.com/qmasingarbe/pymiere/commit/f5b32e5dd6f279ee652c6e76ba552411c12bf78a
