### ISSUE TITLE
Garbled characters appear in Chinese

### ISSUE THREAD

**Issue by qazwsdc** [qmasingarbe/pymiere#2]
example:
```
project = pymiere.objects.app.project
r=project.activeSequence.videoTracks
print ( r[0].clips[0].name )
```

There will be garbled if the clip name have non English character

**Comment by qmasingarbe** [comment]
Hi,
Thank you for reporting this bug. The issue has now been fixed.
I invite you to pull or re-download the Pymiere python library, especially the `pymiere/core.py` file containing the fix.
The code you mentioned above should now work with Chinese or other characters such as letter with accents.
Let me know if everything worked fine.
