### ISSUE TITLE
Feature Request: Change filename default from "playblast"

### ISSUE THREAD

**Issue by PFython** [qmasingarbe/pymiere#20]
I notice "playblast" is the default filename for demo_ui.py import/export/save/load.

A "nice to have" would be for the actual path/filename of the open project to be picked up dynamically, rather than hard coded as it is currently i.e. `default_folder = r"C:\Users\Quentin\Desktop\temp\playblast"`

I'm a recent convert to `pathlib `for file and directory operations, so perhaps overwrite `default_folder` after confirming there is an open project with something like:

    from pathlib import Path
    default_folder = Path(pymiere.objects.app.project.path).parent

**Comment by qmasingarbe** [comment]
Thanks for your suggestion, this commit should implement this behavior https://github.com/qmasingarbe/pymiere/commit/f5b32e5dd6f279ee652c6e76ba552411c12bf78a

**Comment by PFython** [comment]
You've been busy these last 24 hours Quentin!  Many thanks!  👍
