### ISSUE TITLE
demo_ui.py: import_func

### ISSUE THREAD

**Issue by PFython** [qmasingarbe/pymiere#23]
I noticed in `demo_ui.py` the final argument (`importAsNumberedStills`) is given as `True `but the normal expected way of importing clips should IMHO be `False `by default.  It took me quite a while to work out what was going on and why my timeline was looking odd (missing the full video clips), and I fear other new users learning from the demo programs may find this confusing too.

Could I suggest simply changing Line 233 to:
`pymiere.objects.app.project.importFiles([file_to_import], True, root_bin, False)`

**Comment by qmasingarbe** [comment]
The import popup in the `demo_ui.py` only allow you to import one file so this problem never appreared. I agree and fixed it  https://github.com/qmasingarbe/pymiere/commit/56b04f5897e043b4cb3a3d7a6a2bdd49639ecf6a
