### ISSUE TITLE
eval_script filepath issue

### ISSUE THREAD

**Issue by fixinPost** [qmasingarbe/pymiere#29]
Hi, I'm having an issue with the eval_script function from core.py. I can give it a string of extendscript code and that code is executed correctly, but when I try using a file pathstring that points to a jsx, file I get 'EvalScript error.' I'm not sure if it's a syntax error.  I'm currently on Mac, but I had the same issue on windows. 

my code : eval_script('/Users/myUserName/Desktop/stamp.jsx')

I also tried eval_script(r'/Users/myUserName/Desktop/stamp.jsx')

Has anyone else had any issues with this function? I seem to recall being able to do successfully give it file paths when I tested it a few months ago, but now I can't. is it a syntax error on my part? Does anyone else have this problem?

**Comment by qmasingarbe** [comment]
Hi,
You have to use eval_script(filepath="..."). If you don't use the filepath keyword it will try to exec your path as a code line.
Let me know if that worked

**Comment by fixinPost** [comment]
I just tried your advice:
>>> eval_script(filepath= "/Users/myUserName/Desktop/pymiere-master/helloWorld.jsx")
 and received this new error. 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "core.py", line 80, in eval_script
    with open(filepath, encoding='utf-8-sig') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

thank you for your time

**Comment by qmasingarbe** [comment]
Right, there was a compatibility problem for python 2 in the code reading the file. I fixed it, you can update your pymiere from github or pip and you should be able to use your code in python 2.7.
