### ISSUE TITLE
Fails to install the pymiere_link.zxp in Adobe Extension Manager.

### ISSUE THREAD

**Issue by BigRoy** [qmasingarbe/pymiere#3]
### Issue

I can't seem to install the `pymiere_link.zxp` through Adobe Extension Manager UI for the latest version of Adobe Premiere Pro - or I am incorrectly trying to install the file.

![afbeelding](https://user-images.githubusercontent.com/2439881/89198847-131e4c80-d5ae-11ea-892e-e36ed9a58e91.png)

Any pointers on how to get this to work? I'm on Adobe Premiere Pro 2020 on Windows 10.

**Comment by qmasingarbe** [comment]
Hi @BigRoy,
Thanks for reporting this issue. I haven't yet tested Pymiere with Premiere Pro 2020. I will install the latest version, test the extension and let you know as soon as I find the problem.

**Comment by bryhimself** [comment]
Hi,
I'm also on Adobe Premiere Pro 2020 on Windows 10.
I use zxp installer (https://aescripts.com/learn/zxp-installer/) worked fine for me.

I don't know if it's only for my config, but the python environment must be at least 3.7, cause on 3.6 got an issue with => from subprocess import check_output

Also, got issue with the get_installed_software_info() function inside exe_utils, the function returned a bad path or incomplete

so in  get_installed_software_info() function I changed:
exe_path = last_version_info["InstallLocation"]
into:
exe_path = last_version_info["InstallLocation"]+'\\' +last_version_info["DisplayName"]

**Comment by bryhimself** [comment]
Cause in Premiere Pro 14.x the path returned in "InstallLocation" is incomplete

**Comment by bryhimself** [comment]
But anyway it's a very usefull tool.
Congratulation !

**Comment by qmasingarbe** [comment]
Hi @BigRoy ,
I looked into the problem, tried installing the official Vimeo extension for a test and ran into the same issue. I looked at the installation instructions and found that statement from Adobe: 
`Do not use Adobe Extension Manager for CC2015 or later compatible Adobe apps. It is no longer supported and may create install issues. Use a third party utility for extension installation`
My usual method of installation (using ExManCmd) worked fine for Premiere 2020. I updated the installation instructions in the readme to reflect these discovery.
Can you please try one of the methods and let me know if it worked?

**Comment by qmasingarbe** [comment]
Hi @bryhimself ,
Thanks for the zxp installer method, I added it to the readme installation instructions!
I'm creating a new issue for the `get_installed_software_info wrong path`  and the `python 3.6 compatibility` so this issue is dedicated to installation problems

**Comment by BigRoy** [comment]
> My usual method of installation (using ExManCmd) worked fine for Premiere 2020. I updated the installation instructions in the readme to reflect these discovery.

I can confirm that this worked for me too. Good stuff!
