### ISSUE TITLE
Issue with importMGT method

### ISSUE THREAD

**Issue by jmedwarren** [qmasingarbe/pymiere#30]
Hi! First off, thank you so much. This module has been a life saver. I did have an issue when trying to import a mogurt. I'm running Python 3.9.1. and I'm on Premiere 2020.

I used the code in the example documentation here (replacing path with my own mogrt of course):

import pymiere  
from pymiere.wrappers import time_from_seconds  
sequence = pymiere.objects.app.project.activeSequence  
# import mogrt template into sequence  
# path to mogrt (some come with Premiere install in C:\Program Files\Adobe\Adobe Premiere Pro 2020\Essential Graphics)  
mogrt_path = r"C:\path\to\template.mogrt"  
mgt_clip = sequence.importMGT(  
    path=mogrt_path,  
    time=time_from_seconds(1),  # start time  
    videoTrackIndex=1, audioTrackIndex=1  # on which track to place it  
)  
# get component hosting modifiable template properties  
mgt_component = mgt_clip.getMGTComponent()  
# iter through MGT properties, display and change values  
for prop in mgt_component.properties:  
    print(prop.displayName)  
    value = prop.getValue()  
    print(value)  
    prop.setValue(value, True)

And I received this traceback:

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymiere/objects/premiere_objects.py", line 1284, in importMGT
    return TrackItem(**self._eval_on_this_object("importMGT({}, {}, {}, {})".format(_format_object_to_es(path), _format_object_to_es(time), _format_object_to_es(videoTrackIndex), _format_object_to_es(audioTrackIndex))))
TypeError: pymiere.objects.premiere_objects.TrackItem() argument after ** must be a mapping, not NoneType

I've been spinning my wheels and googling hard to try to figure out a solution, so figured I'd just ask. Thank you so much in advance.

**Comment by qmasingarbe** [comment]
Hi and thanks for using pymiere!
Your error seems to indicate that Premiere doesn't suceed in importing the MGT. Can you confirm that you don't see it appearing in your timeline?
This may be due tu an incorrect or malformed path to the mogrt file. I tried the code above on my computer and it worked with a valid path and raised the same error as yours with an invalid path.
Please note that if you're running this on Windows you must write the path with backslashes and prefix the string with an `r` character as in the example documentation.
Please let me know if you manage to solve this with this hint or if you want more infos.

**Comment by qmasingarbe** [comment]
@jmedwarren
Didi you manage to solve your issue?
You can read more about how to manage paths in a windows compliant way here : https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f
I almost sure the path formating is the issue in your case.

**Comment by jmedwarren** [comment]
Thank you so much! I did get it working! Very much appreciate your help.
