### ISSUE TITLE
Can't set a correct value to "Key Color" in the "Ultra Key" effect

### ISSUE THREAD

**Issue by VasylMak** [qmasingarbe/pymiere#32]
Hi! I was try to change the value to - (18374966859398184000), while the default value is (18374686479671623000). For some reason after this line `property.setValue(18374966859398184000, True)` my "Key Color" is still black and the new value is - (0). If I try to change the value to a shorter number like `property.setValue(1837496685, True)` it's work, but the color isn't what I need, and when I add more numbers, the value isn't changed like I expected.

P.s. I just need to change the "Key Color" in "Ultra Key" to "FFFEFE".

Python 3.9, Windows 10.

**Comment by qmasingarbe** [comment]
Hi @VasylMak ,
Thank you for sharing your problem. To query or set a color property on an effect you should use `getColorValue` or `setColorValue` (see usage example bellow). Note that I fixed thoses functions (https://github.com/qmasingarbe/pymiere/commit/fa2f5a789c8810276e8a9a5dc34e1f75d8503f7a) that weren't working properly before so please update Pymiere (via pip or this repo) before using the code bellow.
```
import pymiere
clip = pymiere.objects.app.project.activeSequence.videoTracks[0].clips[0]
ultra_key = [c for c in clip.components if c.displayName == "Ultra Key"][0]
property = [p for p in ultra_key.properties if p.displayName == "Key Color"][0]
print(list(property.getColorValue()))
property.setColorValue(255, 128, 128, 128, True)  # a, r, g, b values 0-255
```
