### ISSUE TITLE
Support for createNewSequenceFromClips?

### ISSUE THREAD

**Issue by rooseveltrp** [qmasingarbe/pymiere#33]
Hi,

Thanks for making this awesome Python wrapper for ExtendScript. The results have been excellent so far.

Seems like it's missing the `createNewSequenceFromClips()` method.

It will be cool if the Python package is in sync with the latest ExtendScript API.

Nevertheless, your work is excellent. I cannot thank you enough.

**Comment by qmasingarbe** [comment]
Hi @rooseveltrp ,

Thanks for your issue. I implemented `createNewSequenceFromClips` in Pymiere. You can update your Pymiere install via pip or via this repo.

Let me know if you find any other missing methods!
