### ISSUE TITLE
How to duplicate a ProjectItem?

### ISSUE THREAD

**Issue by iferencz** [qmasingarbe/pymiere#34]
As title, thank you

**Comment by qmasingarbe** [comment]
Hi @iferencz 
Did you manage to find a solution that suits your needs ? Thanks

**Comment by iferencz** [comment]
@qmasingarbe I didn't find it, but it can be used in after effects. It seems that Premiere does not support this method.
https://ae-scripting.docsforadobe.dev/items/compitem/?highlight=duplicate#compitem-duplicate

**Comment by qmasingarbe** [comment]
Thank you for this information, I will have a look on how to have a similar outcome in Premiere when I get the time!

**Comment by iferencz** [comment]
@qmasingarbe thanks!

**Comment by qmasingarbe** [comment]
Hi @ghost ,
I now have more time to look at issues on Pymiere. I was wondering what you wanted to do exactly.
If you want to duplicate a sequence, you can use `Sequence.clone()` or `pymiere.wrappers.clone_sequence()`.
If you want to actually duplicate a ProjectItem (don't know why?), depending on your use case you may be fine with creating subclips or completely reimporting the same media as a new ProjectItem.

Please let me know more about what you're trying to achieve...
