### ISSUE TITLE
WinError 6

### ISSUE THREAD

**Issue by warped-kings** [qmasingarbe/pymiere#44]
Thank you so much for creating this! I use it every day and it works flawlessly when I run it as a script. 
When I try to create an exe, I get the following error when trying to run it:

`  File "pymiere\objects\start_vars.py", line 56, in app
  File "pymiere\core.py", line 469, in _eval_script_returning_object
  File "pymiere\core.py", line 77, in eval_script
  File "pymiere\core.py", line 30, in check_premiere_is_alive
  File "pymiere\exe_utils.py", line 36, in is_premiere_running
  File "pymiere\exe_utils.py", line 83, in exe_is_running
  File "pymiere\exe_utils.py", line 121, in _get_pids_from_name
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 488, in run
  File "subprocess.py", line 753, in __init__
  File "subprocess.py", line 1090, in _get_handles
OSError: [WinError 6] The handle is invalid`

I was wondering if there was a solution you can think of?

**Comment by BigRoy** [comment]
> When I try to create an exe

Could you describe what it is exactly you're trying to do and with you did exactly to get to this error?

---

The error message itself shows it failing on [this particular call](https://github.com/qmasingarbe/pymiere/blob/56899b1a1f159f61c9ecb20bebf9b836b568bc66/pymiere/exe_utils.py#L121) in the code with an error produced in `subprocess.check_output`. The `[WinError 6] The handle is invalid` might happen if the started process is invalid (e.g. `TASKLIST` won't run as expected) or it cannot receive any STDIN for which [this might be a fix](https://stackoverflow.com/a/40108817).

**Comment by warped-kings** [comment]
Sorry, I should have stated that in my initial post. 
Thank you for those references. The first fix worked for me if I created an exe from the code below. I still get the error when I include it in my main app. Either way, this is exactly what I needed to get it working.

Btw, I used pyinstaller to create an exe of an app.

`def import_clips(dropbox, address):
    project = pymiere.objects.app.project
    media_path = os.path.join(dropbox,address)
    item_path = []
    for file in glob(media_path):
        extention = file
    print('here')
    for ext in ('*.mov','*.mp4'):
        item_path.extend(glob(join(extention,ext)))
        success = project.importFiles(  
        item_path,
        suppressUI=True,  
        targetBin=project.rootItem,
        importAsNumberedStills=False) `
