### ISSUE TITLE
Audio Effects Using QE

### ISSUE THREAD

**Issue by edmundsj** [qmasingarbe/pymiere#45]
Is there an analogous function to ``qe_project.getVideoEffectsList()`` for audio effects? I am trying to apply a noise gate that uses the "dynamics" plugin, and I'm not sure if it is accessible using QE or through some other method.

**Comment by edmundsj** [comment]
Yes, there is, it's called ``getAudioEffectList()``. Found it by running ``pymiere.objects,qe.project.inspect()``. Also, this project is amazing, is there some way I can give you money for making it?

**Comment by qmasingarbe** [comment]
@edmundsj Nice use of `inspect()`
I don't have a donation system but thank you very much for your support!
