### ISSUE TITLE
Missing "save" parameter at pymiere.objects.premiere_objects.py.Project.closeDocument function

### ISSUE THREAD

**Issue by luis10barbo** [qmasingarbe/pymiere#51]
Function now:
```
def closeDocument(self):
        return self._eval_on_this_object("closeDocument()")
```

Problem:
closeDocument() has a bool parameter that determines if the document will be saved at closeup, but pymiere's function doesn't account for it.

by executing `closeDocument("false")`, premiere will quit from the document without saving it.

It would be great if you added a parameter like save:bool to pymiere's function:
```
def closeDocument(self, save=True):
	return self._eval_on_this_object(f"closeDocument({save_document})")
```
then a check to convert from python bool to javascript bool in string
```
def closeDocument(self, save=True):
	save_document = "true" if save == True else "false"
	return self._eval_on_this_object(f"closeDocument({save_document})")
```

**Comment by qmasingarbe** [comment]
Hi @luis10barbo ,
Thank you for reporting this issue.
It has been fixed (ac7def19f0b21274363a41b0f221c6f768c5df43) and is now available in the lastest pymiere release 1.4.0 via pip.
Again thank you for participating in making pymiere better!
