### ISSUE TITLE
ComponentParam getKeys() invalid return type 

### ISSUE THREAD

**Issue by lpequignot** [qmasingarbe/pymiere#54]
Hello, 

I've seen a little omission in ComponentParam.getKeys() method.
The returned object isn't of the correct type. for example,  I got following result.

```
>>> p.sequences[41].videoTracks[1].clips[0].components[2].properties[8].getKeys()
{'pymiere_id': '7UEROfIzdT'}
```

I think it should return an Array and I'm getting the list of keys when I do  

`keys = Array(**self._parameter._eval_on_this_object("getKeys()"))
`
So, it should be:
```
  def getKeys(self):
        return Array(**self._parameter._eval_on_this_object("getKeys()"))
```

Regards,

Louise

**Comment by qmasingarbe** [comment]
Hi @lpequignot ,
Thank you for reporting this issue and providing a fix.
It has been applied (117714aa7f417530e5cec3029b2d270212a630f8) and is now available in the lastest pymiere release 1.4.0 via pip.
Again thank you for participating in making pymiere better!
