### ISSUE TITLE
Add isDoneAnalyzingForVideoEffects

### ISSUE THREAD

**Issue by TrueObsidian** [qmasingarbe/pymiere#56]
I was creating and rendering auto reframe sequences when I noticed premiere will render the sequence before it's finished analyzing. This causes the video to render without any reframing. Adding a while loop solves this.

`while not pymiere.Sequence.isDoneAnalyzingForVideoEffects(auto_reframe_sequence):
    print('Analyzing video effects')
    sleep(1)`

Added this to premiere_objects:
`def isDoneAnalyzingForVideoEffects(self):
        return (self._eval_on_this_object("isDoneAnalyzingForVideoEffects()"))`

**Comment by qmasingarbe** [comment]
Hi @TrueObsidian ,
Thank you for reporting this issue and providing a fix.
It has been applied (7d2d39c66f9c96587a188700fa7019db7d4812ff) and is now available in the lastest pymiere release 1.4.0 via pip.
Again thank you for participating in making pymiere better!
