### ISSUE TITLE
AttributeError: module 'pymiere' has no attribute 'objects'

### ISSUE THREAD

**Issue by dangerstudios** [qmasingarbe/pymiere#59]
weird issue when I try to run this code via a .py file:

`import pymiere
print(pymiere.objects.app.isDocumentOpen())`

**AttributeError: module 'pymiere' has no attribute 'objects'**

if I open python in a shell and manually run that code it works (returns true if premiere is open and breaks if premiere is not open)

anyone else get this?

**Comment by dangerstudios** [comment]
ok got it working, don't name your python file pymiere lol

**Comment by BigRoy** [comment]
This issue can be closed. The issue here was a file `pymiere.py` that conflicted with the actual pymiere package being found on `PYTHONPATH` / `sys.path`.
