### ISSUE TITLE
TypeError from Project.importSequences()

### ISSUE THREAD

**Issue by amirul181** [qmasingarbe/pymiere#61]
I'm trying to implement Project.importSequences() as described [in the Premiere Pro Scripting Guide](https://ppro-scripting.docsforadobe.dev/general/project.html#project-importsequences)

Here is what I did:

`sequenceIDs = ["2714b58d-10a0-4801-9646-8a4f6f1e2a98"]
path = r"E:\path\untitled.prproj"

pymiere.objects.app.project.importSequences(path, sequenceIDs)
`

But I get this error:
TypeError: importSequences() takes 2 positional arguments but 3 were given

Any help is appreciated. Thank you!

**Comment by hedley-david** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/102440609/215281872-eaf514d5-930f-49af-9483-47eca633a65c.png">

It worked for me on a Mac literally substituted my values for yours. Is this maybe a case of the slashes needing to be doubled up in your path name?

**Comment by hedley-david** [comment]
as a follow up, read my post #52 -- it has the exact solution. I had to modify the premiere_objects.py file to get it to work.

**Comment by amirul181** [comment]
Where is this premiere_objects.py file located? 

Thanks.

**Comment by amirul181** [comment]
> <img alt="image" width="685" src="https://user-images.githubusercontent.com/102440609/215281872-eaf514d5-930f-49af-9483-47eca633a65c.png">
> 
> It worked for me on a Mac literally substituted my values for yours. Is this maybe a case of the slashes needing to be doubled up in your path name b/c they're escaping?

I've tried doubling the slashes and it still doesn't work. Thank you, though.

**Comment by qmasingarbe** [comment]
Hi @amirul181 & @hedley-david ,
Thank you for reporting this issue.
There was indeed a problem in the method signature that was not properly replicated. This should be fixed (aa03b3d24d89ef095af428013fb93cde3791d28d) and is now available in the latest pymiere release 1.4.0 via pip.
(if you make sure to use the r letter before the string you don't need to use double slashes)
Again thank you for participating in making pymiere better!
