### ISSUE TITLE
how to use media encoder without premiere？

### ISSUE THREAD

**Issue by Upfunny** [qmasingarbe/pymiere#65]
There are some .prproj files, I want to use media encoder to output them.
I can use premiere open the .prproj and use "pymiere.objects.app.encoder.encodeSequence" to do that,
but I think is there a way to render videos directly with Adobe Media Encoder without using Premiere Pro?

**Comment by qmasingarbe** [comment]
Hi @Upfunny ,
This is outside the scope of pymiere. I can recommend this documentation on how to execute extendscript in Media Encoder from the command line: https://ame-scripting.docsforadobe.dev/guide/index.html#how-do-i-run-scripts-in-ame which seems to be what you want.
