### ISSUE TITLE
Run subprocess check_output and calls without popups

### ISSUE THREAD

**Issue by BigRoy** [qmasingarbe/pymiere#7]
### Issue

Run the `check_output` of subprocess with a hidden window to avoid the extra `cmd` popup.

We can pass the `CREATE_NO_WINDOW` bits for creation flags:

```python
CREATE_NO_WINDOW = 0x08000000

check_output(call, creationflags=CREATE_NO_WINDOW)
```

See also [here](https://stackoverflow.com/a/25124003/1838864).

Is there any reason in this case not to do so? 

I quickly added it to the subprocess calls in `pymiere.exe_utils` and it seemed to work. Tested in Python 2.7 (sorry, old Python I had laying around).

**Comment by qmasingarbe** [comment]
In my setup, even without the flag set I don't get any cmd popups when using the exe_utils functions with check_output... I don't know why, I tested it on Win10, python 2.7/3.6/3.7
I added the flag anyway as it had no impact on my tests.
See commit https://github.com/qmasingarbe/pymiere/commit/8b4d15154f7dc00abee7a8d3b3ed00a37e3c4f3c
