### ISSUE TITLE
Can we remove the need for .bat file to start Premiere?

### ISSUE THREAD

**Issue by BigRoy** [qmasingarbe/pymiere#8]
### Issue

It seems the `.bat` file was introduced to not start Premiere Pro as the child process of the Python process. However, I believe that is also possible from subprocess directly.

```python
# pseudocode
import subprocess

CREATE_NEW_CONSOLE = 0x00000010
subprocess.Popen(call, creationflags=CREATE_NEW_CONSOLE)
```

For example also used [here](https://github.com/getavalon/core/blob/94aee92b1bbd8b0e54b47c484d0471cf411ce78a/avalon/lib.py#L221-L226). That code can start applications just fine without it keeping parent connections with the Python process.

Would this be applicable and usable for `pymiere` to start Premiere too?

**Comment by qmasingarbe** [comment]
I did some testing, if I execute the py in a simple console interpreter, Premiere seems to stay open when I kill the script or console. I only have the problem when running the script inside Pycharm, if I stop the script Premiere exits. Maybe Pycharm does some magic to kill processes on python stop?
Anyway I added your solution as the default and left the old .bat trick available as a function argument
@BigRoy thank you for telling me about those creationflags!
